# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

#ibmi-fix-repo-sample.yml 
#The sample file is to provide an example about how to manipulate the PTF database
---
- hosts: all
  gather_facts: false
  collections:
   - ibm.power_ibmi

  tasks:
    - name: query_a_single_group
      ibmi_fix_group_check:
        groups:
          - "SF99737"
      register: single_group

    - name: display_a_single_group
      debug:
        msg: "{{ single_group }}"
