# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- hosts: all
  gather_facts: false
  collections:
    - ibm.power_ibmi

  vars:
    user_profile: ludo
    become_user_name: null
    become_user_password: null

  tasks:
    - name: disk status
      ibmi_sql_query:
        sql: "With iLevel(iVersion, iRelease) AS
             (select OS_VERSION, OS_RELEASE from sysibmadm.env_sys_info)
             SELECT P.*
             FROM iLevel, systools.group_ptf_currency P
             WHERE ptf_group_release = 'R' CONCAT iVersion CONCAT iRelease concat '0'
                   ORDER BY ptf_group_level_available -
                   ptf_group_level_installed DESC;"
                  
        become_user: '{{ become_user_name }}'
        become_user_password: '{{ become_user_password }}'
      register: disk_status
      tags: disk_status
      ignore_errors: true
    - debug:
       var: disk_status

    - name: create result to file ludo.txt
      copy: 
        content: "{{ disk_status.row }}"
        dest: /home/{{ user_profile }}/ptfs.txt   
