# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- hosts: all
  gather_facts: false
  collections:
    - ibm.power_ibmi

  vars:
    become_user_name: null
    become_user_password: null

  tasks:
    - name: system status
      ibmi_sql_query:
        sql: "SELECT *
                  FROM TABLE(QSYS2.SYSTEM_STATUS (RESET_STATISTICS=>'YES')) X;"
                  
        become_user: '{{ become_user_name }}'
        become_user_password: '{{ become_user_password }}'
      register: system_status
      tags: system_status
      ignore_errors: true
    - name: copy
      copy:
        content: "{{ system.status | from_yaml }}"
        dest: "/home/menard/ludo1.csv"
    - debug:
       var: system_status
