---
- hosts: all
  gather_facts: false
  collections:
    - ibm.power_ibmi

  vars:
    user_profile: ludo
    become_user_name: null
    become_user_password: null

  tasks:
    - name: disk status
      ibmi_sql_query:
        sql: "SELECT distinct unit_number, disk_type,
                     DEC(unit_storage_capacity/1000000000,4) AS capacity, percent_used
                     FROM qsys2.sysdiskstat
                     WHERE resource_status = 'ACTIVE';"
                  
        become_user: '{{ become_user_name }}'
        become_user_password: '{{ become_user_password }}'
      register: disk_status
      tags: disk_status
      ignore_errors: true
    - debug:
       var: disk_status

    #- name: create result to file ludo.txt
    #  copy: 
    #    content: "{{ disk_status.row }}"
    #    dest: /home/{{ user_profile }}/ludo.txt   

    - name: template CSV
      template:
        src: generate_csv.j2
        dest: /home/{{ user_profile }}/disk_list.xls
