---
- hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi

  tasks:
    
    - name: create user profile {{user_profil}}
      ibmi_user_and_group:
        operation: 'create'
        user: '{{user_profil}}'
        user_class: '*SECOFR'
      register: user_result
    - debug:
       var: user_result

    - name: display user profile {{user_profil}}
      ibmi_user_and_group:
        operation: 'display'
        user: '{{user_profil}}'
